# Generated by Django 4.1.1 on 2022-11-18 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoCivil',
            fields=[
                ('estadoCivilId', models.IntegerField(primary_key=True, serialize=False)),
                ('estadoCivil', models.CharField(choices=[('soltero', 'Soltero'), ('casado', 'Casado')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TipoSolicitud',
            fields=[
                ('tipoSolicitudId', models.IntegerField(primary_key=True, serialize=False)),
                ('tipoSolicitud', models.CharField(choices=[('soltero', 'Soltero'), ('casado', 'Casado')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id_solicitud', models.IntegerField(primary_key=True, serialize=False)),
                ('nombres', models.TextField(max_length=20)),
                ('apPaterno', models.TextField(max_length=20)),
                ('apMaterno', models.TextField(max_length=20)),
                ('rut', models.IntegerField()),
                ('dv', models.TextField(max_length=20)),
                ('fnacimiento', models.DateField()),
                ('donante', models.BooleanField(max_length=20)),
                ('observaciones', models.TextField(max_length=20)),
                ('estado_civil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.estadocivil')),
                ('tipo_solicitud', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.tiposolicitud')),
            ],
        ),
    ]
