# Generated by Django 4.1.1 on 2022-11-18 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadocivil',
            name='estadoCivilId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='id_solicitud',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tiposolicitud',
            name='tipoSolicitudId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
