# Generated by Django 4.1.1 on 2022-11-18 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_alter_estadocivil_estadocivil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='apMaterno',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='apPaterno',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='dv',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='nombres',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='observaciones',
            field=models.CharField(max_length=20),
        ),
    ]
