# Generated by Django 4.1.1 on 2022-11-26 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_alter_solicitud_fsolicitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='estado_civil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.estadocivil'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='tipo_solicitud',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.tiposolicitud'),
        ),
    ]
